version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: iam-postgres
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6r5Z01Yz1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  iam:
    build: .
    container_name: iam-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/iam_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 6r5Z01Yz1
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - postgres

volumes:
  postgres_data:
